### PR TITLE
feat: Added IndexNow

### PR DESCRIPTION
**Pull request by saigkill**
This Pullrequest adds the IndexNow Service.

### CODE REVIEW

**Comment by EdiWang** [comment]
Despite the problems in this PR, I appreciate the idea of adding IndexNow. I will plan this feature in v14.10. Thank for your contribution @saigkill

**Comment by EdiWang** [comment]
Close via #818

**Comment by saigkill** [comment]
For Documentation purposes. Using IndexNow needs a API Key as a file. This post holds a API Key Generator and further information: [https://www.bing.com/indexnow/getstarted](https://www.bing.com/indexnow/getstarted)

**Comment by EdiWang** [comment]
API key txt file is handled by https://github.com/EdiWang/Moonglade/blob/master/src/Moonglade.IndexNow.Client/IndexNowMapHandler.cs no need to upload file to website root

**Comment by EdiWang** [comment]
Hi @saigkill 

Just FYI, v14.10.0-rc.2 got IndexNow working for happy path now.

There are still cases like 429 error that can occur when you update a published post too often, which need extra amount of work to handle in next release.

Thank you again for your great idea

**Comment by saigkill** [comment]
@EdiWang Thank you very much. Your implementation was better than mine. I learned a few new things now :-)

**Pull request closed without merging**
