### PR TITLE
Fix running errors in docker(linux) environment.

### PR DESCRIPTION
**Pull request by zhiyongpeng**
When I uploading an image in the docker(linux) environment, an exception occurred in moonglade, which is `SixLabors.Fonts.Exceptions.FontFamilyNotFoundException: Arial could not be found`. The Arial font exists by default in Windows system,but not in docker(Linux). Therefore, we need to install the fonts required by `SixLabors` into docker(Linux).
Reference link: https://stackoverflow.com/questions/60934639/install-fonts-in-linux-container-for-asp-net-core

### CODE REVIEW

**Comment by EdiWang** [comment]
This is wired, when running in Linux + Docker, Moonglade should be using "OpenSans" font which was already copied in Dockerfile. Installing Windows fonts may have legal issues.

**Comment by zhiyongpeng** [comment]
@EdiWang This issue is not caused by `Edi.Captcha`, but `Edi.ImageWatermark`, which is needed to add watermark to the image when uploading.

**Comment by EdiWang** [comment]
Thanks @zhiyongpeng I get it. I'll fix this in Edi.ImageWatermark library.

**Comment by zhiyongpeng** [comment]
That’s OK. After you fixed the bug in `Edi.ImageWatermark`,I will remove the font installation setting in dockerfile. Please reject this PR.

**Pull request closed without merging**
