### PR TITLE
Prevent automated scanner as well as improving performance

### PR DESCRIPTION
**Pull request by EdiWang**
Address #338

### CODE REVIEW

**Comment by Anduin2017** [comment]
While this is a nice fix, your regex expression is super hard to read. Why not copy it to a const var?

**Comment by EdiWang** [comment]
@Anduin2017 good catch, I will work 996 and refact the code

**Comment by EdiWang** [comment]
@Anduin2017 

Consts is a no go, code will end up like this:

```csharp
[Route("list/{categoryName:regex(" + WebConsts.ROUTE_REGEX_SLUG + ")}")]
```

And this won't compile:
```csharp
[Route($"list/{{categoryName:regex({WebConsts.ROUTE_REGEX_SLUG})}}")]
```

**Comment by Anduin2017** [comment]
F**k C# compiler.

**Pull request merged**
