### PR TITLE
refactor: Added possibility to use the GithubAPI. 

### PR DESCRIPTION
**Pull request by saigkill**
This Pull Request enables a option to access the Github Api. Currently implemented is the request for Repositories from the user.
Users Full path to Github Profile is saved into SocialProfileSettings. Also there are a possibility to add some other Social Profile Links. So they can used into custom pages.

### CODE REVIEW

**Comment by WeihanLi** [comment]
@EdiWang maybe we could use `dotnet-format` to unify the code style and verify the code style when PR drafted

**Comment by saigkill** [comment]
@WeihanLi Thanks for your comment. I haven't noticed, that Mads Kristensens "Code Cleanup on Save" was enabled. I used dotnet format on my last PR. So it should be better.

**Comment by EdiWang** [comment]
This design is providing fixed number of third party links. A better approach is to let user add any number of links with icons they want. So providing a UI with a JSON editor would be better, since Moonglade users are all developers. Just like how the "Custom menus" is designed.

image

**Comment by saigkill** [comment]
@EdiWang I think that would be the best option. Maybe we can provide some predefined tags for that. Maybe the user creates a new link and set a provider tag, what can be "Linkedin" or "Facebook". So wen can ensure, that we can find a specific entry by its provider name. I will look at your code for the menu.

**Comment by EdiWang** [comment]
Close as tracked by #831

**Pull request closed without merging**
