### PR TITLE
Enable nullable

### PR DESCRIPTION
**Pull request by Anduin2017**

### CODE REVIEW

**Comment by EdiWang** [comment]
Please fix build warnings or revert the nullable switch on csproj files.

**Comment by Anduin2017** [comment]
> Please fix build warnings or revert the nullable switch on csproj files.

752 warnings. Too 996 to fix.

**Comment by Anduin2017** [comment]
> Please fix build warnings or revert the nullable switch on csproj files.

Maybe you can merge this so you can see those possible null reference warnings in the code and fix those later.

**Comment by EdiWang** [comment]
Close by violence since @Anduin2017 is my friend, he won't be angry.

**Pull request closed without merging**
